name: Daily Scraper Automation

on:
  schedule:
    - cron: "0 10 * * *" # Runs every day at 10 AM UTC
  workflow_dispatch: # Allow manual run

jobs:
  run-daily-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Or your project's python version

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          uv add -r req.txt

      - name: Run Scraper Script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GOOGLE_CREDS_FILE: ${{ secrets.GOOGLE_CREDS_FILE }}
          GOOGLE_SCRIPT_URL: ${{ secrets.GOOGLE_SCRIPT_URL }}
          URL: ${{ secrets.URL }}
        run: |
          uv run main.py
